// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: atom_ui

#ifndef _ATOM_UI_UI_H
#define _ATOM_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_statusBar;
extern lv_obj_t *ui_wifiMode;
extern lv_obj_t *ui_wifiIcon;
extern lv_obj_t *ui_atomLabel;
extern lv_obj_t *ui_batteryIcon;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_timePanel;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_wifi_png);   // assets\WIFI.png
LV_IMG_DECLARE( ui_img_battery_png);   // assets\BATTERY.png
LV_IMG_DECLARE( ui_img_link_png);   // assets\LINK.png
LV_IMG_DECLARE( ui_img_time_png);   // assets\TIME.png
LV_IMG_DECLARE( ui_img_follows_png);   // assets\FOLLOWS.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
