// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: atom_ui

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel6, lv_pct(100));
    lv_obj_set_height(ui_Panel6, lv_pct(100));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel5, lv_pct(100));
    lv_obj_set_height(ui_Panel5, lv_pct(100));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusBar1 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_statusBar1, 320);
    lv_obj_set_height(ui_statusBar1, 18);
    lv_obj_set_x(ui_statusBar1, 0);
    lv_obj_set_y(ui_statusBar1, -10);
    lv_obj_set_align(ui_statusBar1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_statusBar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusBar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_statusBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiMode1 = lv_label_create(ui_statusBar1);
    lv_obj_set_width(ui_wifiMode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiMode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiMode1, 20);
    lv_obj_set_y(ui_wifiMode1, 0);
    lv_obj_set_align(ui_wifiMode1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifiMode1, "STA");
    lv_obj_set_style_text_font(ui_wifiMode1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiIcon1 = lv_img_create(ui_statusBar1);
    lv_img_set_src(ui_wifiIcon1, &ui_img_wifi_closed_png);
    lv_obj_set_width(ui_wifiIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiIcon1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_wifiIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_atomLabel1 = lv_label_create(ui_statusBar1);
    lv_obj_set_width(ui_atomLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_atomLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_atomLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_atomLabel1, "ATOM");
    lv_obj_set_style_text_font(ui_atomLabel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryIcon1 = lv_img_create(ui_statusBar1);
    lv_img_set_src(ui_batteryIcon1, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batteryIcon1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_batteryIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batteryIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_statusBar1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -20);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label8, "92%");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timePanel1 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_timePanel1, 170);
    lv_obj_set_height(ui_timePanel1, 96);
    lv_obj_set_x(ui_timePanel1, 0);
    lv_obj_set_y(ui_timePanel1, -12);
    lv_obj_set_align(ui_timePanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timePanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timePanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_timePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hourMinPanel1 = lv_obj_create(ui_timePanel1);
    lv_obj_set_width(ui_hourMinPanel1, 114);
    lv_obj_set_height(ui_hourMinPanel1, 50);
    lv_obj_set_x(ui_hourMinPanel1, 0);
    lv_obj_set_y(ui_hourMinPanel1, -10);
    lv_obj_set_align(ui_hourMinPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hourMinPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hourMinPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourMinPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hourMinPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minRoller3 = lv_roller_create(ui_hourMinPanel1);
    lv_roller_set_options(ui_minRoller3, "1\n2\n3\n4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_minRoller3, 28);
    lv_obj_set_height(ui_minRoller3, 42);
    lv_obj_set_x(ui_minRoller3, 40);
    lv_obj_set_y(ui_minRoller3, 0);
    lv_obj_set_align(ui_minRoller3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_minRoller3, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minRoller3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_minRoller3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minRoller3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_minRoller4 = lv_roller_create(ui_hourMinPanel1);
    lv_roller_set_options(ui_minRoller4, "1\n2\n3\n4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_minRoller4, 28);
    lv_obj_set_height(ui_minRoller4, 42);
    lv_obj_set_x(ui_minRoller4, 20);
    lv_obj_set_y(ui_minRoller4, 0);
    lv_obj_set_align(ui_minRoller4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_minRoller4, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minRoller4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minRoller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minRoller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_minRoller4, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minRoller4, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_hourMinPanel1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, ":");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hourRoller3 = lv_roller_create(ui_hourMinPanel1);
    lv_roller_set_options(ui_hourRoller3, "1\n2\n3\n4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_hourRoller3, 28);
    lv_obj_set_height(ui_hourRoller3, 42);
    lv_obj_set_x(ui_hourRoller3, -20);
    lv_obj_set_y(ui_hourRoller3, 0);
    lv_obj_set_align(ui_hourRoller3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_hourRoller3, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourRoller3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hourRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hourRoller3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourRoller3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_hourRoller4 = lv_roller_create(ui_hourMinPanel1);
    lv_roller_set_options(ui_hourRoller4, "1\n2\n3\n4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_hourRoller4, 28);
    lv_obj_set_height(ui_hourRoller4, 42);
    lv_obj_set_x(ui_hourRoller4, -40);
    lv_obj_set_y(ui_hourRoller4, 0);
    lv_obj_set_align(ui_hourRoller4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_hourRoller4, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourRoller4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourRoller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hourRoller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hourRoller4, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourRoller4, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_timePanel1);
    lv_bar_set_value(ui_Bar1, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 140);
    lv_obj_set_height(ui_Bar1, 3);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 10);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x2A82E4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_timePanel1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label15, "Wed");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_timePanel1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label16, "2023-4-15");
    lv_obj_set_style_text_letter_space(ui_Label16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel2, 285);
    lv_obj_set_height(ui_Panel2, 66);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 80);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image5, &ui_img_link_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 26);
    lv_obj_set_y(ui_Label17, 3);
    lv_label_set_text(ui_Label17, "PING: 45ms");
    lv_obj_set_style_text_letter_space(ui_Label17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image6, &ui_img_time_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -92);
    lv_obj_set_y(ui_Image6, 0);
    lv_obj_set_align(ui_Image6, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label18, 86);
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, 2);
    lv_obj_set_align(ui_Label18, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label18, "START: 40s");
    lv_obj_set_style_text_letter_space(ui_Label18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image7, &ui_img_follows_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 26);
    lv_obj_set_y(ui_Label19, 0);
    lv_obj_set_align(ui_Label19, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label19, "FOLLOWS: 45");
    lv_obj_set_style_text_letter_space(ui_Label19, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image8, &ui_img_follows_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -92);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label20, 86);
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label20, "APPS: 8");
    lv_obj_set_style_text_letter_space(ui_Label20, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel7, 36);
    lv_obj_set_height(ui_Panel7, 240);
    lv_obj_set_x(ui_Panel7, 33);
    lv_obj_set_y(ui_Panel7, 2);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Panel7, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel7, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel7, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Panel7);
    lv_obj_set_width(ui_Button2, 36);
    lv_obj_set_height(ui_Button2, 42);
    lv_obj_set_x(ui_Button2, -10);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x2A82E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Button2);
    lv_img_set_src(ui_Image10, &ui_img_app_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
