// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: atom_ui

#ifndef _ATOM_UI_UI_H
#define _ATOM_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void anim_down_Animation(lv_obj_t * TargetObject, int delay);
void anim_zoom_fade_out_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_statusBar;
extern lv_obj_t * ui_wifiMode;
extern lv_obj_t * ui_wifiIcon;
extern lv_obj_t * ui_atomLabel;
extern lv_obj_t * ui_batteryIcon;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_timePanel;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_hourMinPanel;
extern lv_obj_t * ui_minRoller2;
extern lv_obj_t * ui_minRoller1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_hourRoller2;
extern lv_obj_t * ui_hourRoller1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_wifi_closed_png);    // assets\WIFI_CLOSED.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets\BATTERY.png
LV_IMG_DECLARE(ui_img_link_png);    // assets\LINK.png
LV_IMG_DECLARE(ui_img_time_png);    // assets\TIME.png
LV_IMG_DECLARE(ui_img_follows_png);    // assets\FOLLOWS.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
